[package]
name = "thumbhash"
version = "0.1.0"
edition = "2021"
description = "A very compact representation of an image placeholder"
license = "MIT"
repository = "https://github.com/evanw/thumbhash"
